"""Generate the Colab notebook suite for the revision workflow.

Run from repo root:
    python scripts/revision/create_revision_notebooks.py

The notebooks are intentionally lightweight runbooks. Heavy experiment logic
should live in scripts so the same commands can be run from Colab, local
shells, or CI-style checks.
"""

from __future__ import annotations

import json
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[2]
NOTEBOOK_DIR = PROJECT_ROOT / "notebooks"


SETUP_CODE = """from pathlib import Path
import json
import os
import subprocess

try:
    from google.colab import drive
    drive.mount('/content/drive')
except Exception as exc:
    print(f'Drive mount skipped or already mounted: {exc}')

DRIVE_ROOT = Path('/content/drive/MyDrive/ECG-Ramba')
REPO_URL = 'https://github.com/BrianNguyen29/ECG-RAMBA.git'
BRANCH = os.environ.get('ECG_RAMBA_BRANCH', 'main')
REPO_DIR = DRIVE_ROOT / 'ECG-RAMBA'

os.environ['ECG_RAMBA_DRIVE_ROOT'] = str(DRIVE_ROOT)

def _run_setup(cmd, cwd=None, check=True):
    print(f'$ {cmd}')
    return subprocess.run(cmd, shell=True, cwd=str(cwd) if cwd else None, check=check)

if (REPO_DIR / '.git').exists():
    os.chdir(REPO_DIR)
    _run_setup('git fetch origin')
    current_branch = subprocess.check_output(
        'git branch --show-current',
        shell=True,
        text=True,
    ).strip()
    if current_branch != BRANCH:
        _run_setup(f'git checkout {BRANCH}')
    _run_setup(f'git pull --ff-only --autostash origin {BRANCH}')
elif (REPO_DIR / 'configs' / 'config.py').exists():
    os.chdir(REPO_DIR)
    print('Repo directory exists but is not a git checkout; skipping git pull.')
elif Path.cwd().joinpath('configs', 'config.py').exists():
    REPO_DIR = Path.cwd()
    os.chdir(REPO_DIR)
    if (REPO_DIR / '.git').exists():
        _run_setup('git fetch origin')
        _run_setup(f'git pull --ff-only --autostash origin {BRANCH}', check=False)
else:
    DRIVE_ROOT.mkdir(parents=True, exist_ok=True)
    _run_setup(f'git clone -b {BRANCH} {REPO_URL} {REPO_DIR}')
    os.chdir(REPO_DIR)

os.chdir(REPO_DIR)
_run_setup('git status --short --branch', check=False)

print('cwd       :', Path.cwd())
print('drive_root:', DRIVE_ROOT)
print('repo_dir  :', REPO_DIR)
print('branch    :', BRANCH)
"""


RUN_HELPER_CODE = """def run(cmd, check=True):
    print(f'$ {cmd}')
    return subprocess.run(cmd, shell=True, check=check)


def run_script_if_exists(script_path, command):
    path = Path(script_path)
    if path.exists():
        run(command)
    else:
        print(f'SKIP: {script_path} is not implemented yet.')
        print(f'Planned command: {command}')
"""


def markdown(text: str) -> dict:
    return {"cell_type": "markdown", "metadata": {}, "source": text.splitlines(keepends=True)}


def code(text: str) -> dict:
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": text.splitlines(keepends=True),
    }


def write_notebook(path: Path, title: str, cells: list[dict]) -> None:
    notebook = {
        "cells": [
            markdown(f"# {title}\n\nGenerated by `scripts/revision/create_revision_notebooks.py`.\n"),
            *cells,
        ],
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3",
            },
            "language_info": {"name": "python", "version": "3.12"},
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(notebook, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"Wrote {path.relative_to(PROJECT_ROOT)}")


def bootstrap_notebook() -> list[dict]:
    return [
        markdown(
            "## Purpose\n\n"
            "Use this first when opening Colab directly. It mounts Drive, checks large "
            "artifacts, then clones or updates the GitHub branch used as the code "
            "transport layer."
        ),
        code(
            """from pathlib import Path
import os
import subprocess

try:
    from google.colab import drive
    drive.mount('/content/drive')
except Exception as exc:
    print(f'Drive mount skipped or already mounted: {exc}')

DRIVE_ROOT = Path('/content/drive/MyDrive/ECG-Ramba')
REPO_DIR = DRIVE_ROOT / 'ECG-RAMBA'
REPO_URL = 'https://github.com/BrianNguyen29/ECG-RAMBA.git'
BRANCH = 'revision/colab-pipeline'
os.environ['ECG_RAMBA_DRIVE_ROOT'] = str(DRIVE_ROOT)

print('drive_root:', DRIVE_ROOT)
print('repo_dir  :', REPO_DIR)
print('branch    :', BRANCH)
"""
        ),
        markdown("## Verify Drive Artifacts"),
        code(
            """required_files = [
    'WFDB-ChapmanShaoxing.zip',
    'PTB-XL.zip',
    'Georgia.zip',
]

missing = []
for name in required_files:
    path = DRIVE_ROOT / name
    print(f'{name}: exists={path.exists()} path={path}')
    if not path.exists():
        missing.append(str(path))

model_dir = DRIVE_ROOT / 'model'
fold_ckpts = sorted(model_dir.glob('fold*_best.pt'))
pca_path = model_dir / 'global_pca_zeroshot.pkl'
print('\\nmodel_dir       :', model_dir)
print('fold checkpoints:', len(fold_ckpts))
print('global PCA      :', pca_path.exists())

if len(fold_ckpts) < 5:
    missing.append(f'Expected 5 fold*_best.pt files under {model_dir}')
if not pca_path.exists():
    missing.append(str(pca_path))
if missing:
    raise FileNotFoundError('Missing required Drive artifacts:\\n' + '\\n'.join(missing))
"""
        ),
        markdown("## Clone Or Update Repo"),
        code(
            """def run(cmd, cwd=None):
    print(f'$ {cmd}')
    subprocess.run(cmd, shell=True, cwd=str(cwd) if cwd else None, check=True)

if (REPO_DIR / '.git').exists():
    run('git fetch origin', cwd=REPO_DIR)
    run(f'git checkout {BRANCH}', cwd=REPO_DIR)
    run(f'git pull --ff-only origin {BRANCH}', cwd=REPO_DIR)
elif REPO_DIR.exists() and any(REPO_DIR.iterdir()):
    raise RuntimeError(f'{REPO_DIR} exists but is not a git repo. Rename it or set REPO_DIR to another folder.')
else:
    REPO_DIR.parent.mkdir(parents=True, exist_ok=True)
    run(f'git clone -b {BRANCH} {REPO_URL} {REPO_DIR}')

os.chdir(REPO_DIR)
run('git status --short --branch')
"""
        ),
        markdown("## Install Lightweight Dependencies"),
        code("!python --version\n!pip install -q numpy==1.26.4 pandas scipy scikit-learn tqdm wfdb joblib matplotlib seaborn packaging neurokit2 iterative-stratification thop\n"),
        markdown("## Run A0 Audit"),
        code("os.environ['ECG_RAMBA_DRIVE_ROOT'] = str(DRIVE_ROOT)\nos.chdir(REPO_DIR)\n!python scripts/revision/00_audit_protocol.py\n"),
    ]


def a0_notebook() -> list[dict]:
    return [
        markdown("## Setup"),
        code(SETUP_CODE),
        markdown("## Revision Plan Files"),
        code(
            """import pandas as pd

for path in [
    'docs/revision_plan/task_board.csv',
    'docs/revision_plan/claim_evidence_map.csv',
    'docs/revision_plan/experiment_registry.csv',
]:
    print('\\n' + path)
    display(pd.read_csv(path).head(20))
"""
        ),
        markdown("## Run Protocol Audit"),
        code("!python scripts/revision/00_audit_protocol.py\n"),
        markdown("## Inspect Audit Warnings"),
        code(
            """audit = json.loads(Path('reports/revision/audit_protocol.json').read_text(encoding='utf-8'))
print('Warnings:')
for warning in audit.get('warnings', []):
    print('-', warning)

print('\\nDataset paths:')
for key, info in audit['artifacts'].get('dataset_paths', {}).items():
    print(f\"{key}: exists={info['exists']} path={info['path']}\")
"""
        ),
        markdown("## Inventory Current Artifacts"),
        code("!python scripts/revision/05_artifact_inventory.py\n"),
    ]


def predictions_notebook() -> list[dict]:
    return [
        markdown("## Setup"),
        code(SETUP_CODE + "\n" + RUN_HELPER_CODE),
        markdown(
            "## Install Base Dependencies\n\n"
            "This notebook can run directly after opening in Colab. These packages "
            "cover data loading, feature extraction, metrics, and artifact checks."
        ),
        code(
            """INSTALL_BASE_DEPS = True
if INSTALL_BASE_DEPS:
    !python --version
    !pip install -q numpy==1.26.4 scipy==1.11.4 pandas scikit-learn threadpoolctl tqdm wfdb joblib matplotlib seaborn packaging neurokit2 iterative-stratification thop einops ninja
else:
    print('Skipping base dependency install.')
"""
        ),
        markdown("## Install Model Dependencies"),
        code(
            """INSTALL_MODEL_DEPS = True
DOWNLOAD_MAMBA_WHEELS_IF_MISSING = True
AUTO_PIN_TORCH_FOR_MAMBA = True
RESTART_RUNTIME_AFTER_TORCH_PIN = True

if INSTALL_MODEL_DEPS:
    import hashlib
    import json
    import os
    import re
    import subprocess
    import sys
    import urllib.request

    import torch

    py_tag = f"cp{sys.version_info.major}{sys.version_info.minor}"
    torch_major_minor = ".".join(torch.__version__.split("+")[0].split(".")[:2])
    cuda_version = torch.version.cuda or ""
    cuda_tag = f"cu{cuda_version.split('.')[0]}" if cuda_version else None
    abi_tag = "TRUE" if torch._C._GLIBCXX_USE_CXX11_ABI else "FALSE"

    wheel_cache_dir = DRIVE_ROOT / f"mamba_wheels_py{sys.version_info.major}{sys.version_info.minor}"
    legacy_dirs = [
        Path("/content/drive/MyDrive") / wheel_cache_dir.name,
        Path("/content/drive/MyDrive/mamba_wheels_py312"),
        DRIVE_ROOT / "mamba_wheels_py312",
    ]
    explicit_wheel_dirs = []
    for p in [wheel_cache_dir, *legacy_dirs]:
        if p not in explicit_wheel_dirs:
            explicit_wheel_dirs.append(p)

    print("Mamba wheel environment")
    print("  Python tag :", py_tag)
    print("  torch      :", torch.__version__)
    print("  CUDA       :", cuda_version or "CPU")
    print("  CUDA tag   :", cuda_tag or "none")
    print("  CXX11 ABI  :", abi_tag)
    print("  cache dir  :", wheel_cache_dir)

    if cuda_tag is None:
        raise RuntimeError("CUDA-enabled PyTorch is required. In Colab, select a GPU runtime before running this notebook.")

    release_cache = {}

    def sha256_file(path: Path) -> str:
        h = hashlib.sha256()
        with path.open("rb") as f:
            for chunk in iter(lambda: f.read(1024 * 1024), b""):
                h.update(chunk)
        return h.hexdigest()

    def wheel_role(path_or_name) -> str | None:
        name = Path(path_or_name).name
        if name.startswith("causal_conv1d-"):
            return "causal"
        if name.startswith("mamba_ssm-"):
            return "mamba"
        return None

    def compatible_wheel(path_or_name, role: str, torch_minor: str | None = None) -> bool:
        name = Path(path_or_name).name
        if wheel_role(name) != role:
            return False
        torch_minor = torch_minor or torch_major_minor
        required = [
            f"{py_tag}-{py_tag}",
            "linux_x86_64.whl",
            f"torch{torch_minor}",
            f"cxx11abi{abi_tag}",
        ]
        if cuda_tag:
            required.append(cuda_tag)
        return all(token in name for token in required)

    def list_wheels():
        wheels = []
        for wheel_dir in explicit_wheel_dirs:
            if wheel_dir.exists():
                wheels.extend(sorted(wheel_dir.glob("*.whl")))
        return sorted(set(wheels))

    def select_cached_wheels():
        wheels = list_wheels()
        if wheels:
            print(f"Found {len(wheels)} wheel file(s) in configured Drive cache folders.")
            for p in wheels[:60]:
                flag = "compatible" if compatible_wheel(p, wheel_role(p) or "") else "present"
                print(f"  - {p.name} [{flag}]")
            if len(wheels) > 60:
                print(f"  ... {len(wheels) - 60} more wheel(s)")
        causal = [p for p in wheels if compatible_wheel(p, "causal")]
        mamba = [p for p in wheels if compatible_wheel(p, "mamba")]
        return (causal[0] if causal else None), (mamba[0] if mamba else None)

    def github_latest_release(repo: str) -> dict:
        if repo in release_cache:
            return release_cache[repo]
        url = f"https://api.github.com/repos/{repo}/releases/latest"
        req = urllib.request.Request(url, headers={"User-Agent": "ECG-RAMBA-Colab"})
        with urllib.request.urlopen(req, timeout=60) as resp:
            release_cache[repo] = json.loads(resp.read().decode("utf-8"))
        return release_cache[repo]

    def asset_torch_minor(asset_name: str, role: str) -> str | None:
        if wheel_role(asset_name) != role:
            return None
        required = [
            f"{py_tag}-{py_tag}",
            "linux_x86_64.whl",
            f"cxx11abi{abi_tag}",
        ]
        if cuda_tag:
            required.append(cuda_tag)
        if not all(token in asset_name for token in required):
            return None
        m = re.search(r"torch([0-9]+\\.[0-9]+)", asset_name)
        return m.group(1) if m else None

    def release_supported_torch_minors(repo: str, role: str) -> set[str]:
        rel = github_latest_release(repo)
        minors = {
            minor for asset in rel.get("assets", [])
            if (minor := asset_torch_minor(asset["name"], role)) is not None
        }
        return minors

    def torch_minor_key(minor: str) -> tuple[int, int]:
        major, minor_part = minor.split(".", 1)
        return int(major), int(minor_part)

    def choose_supported_torch_minor() -> tuple[str | None, list[str]]:
        causal_minors = release_supported_torch_minors("Dao-AILab/causal-conv1d", "causal")
        mamba_minors = release_supported_torch_minors("state-spaces/mamba", "mamba")
        common = sorted(causal_minors & mamba_minors, key=torch_minor_key)
        common_stable = [m for m in common if m.startswith("2.")]
        if torch_major_minor in common:
            return torch_major_minor, common

        requested = os.environ.get("ECG_RAMBA_TORCH_MINOR")
        if requested:
            if requested not in common:
                raise RuntimeError(f"ECG_RAMBA_TORCH_MINOR={requested} is not supported by both Mamba wheel releases: {common}")
            return requested, common

        lower_or_equal = [
            m for m in common_stable
            if torch_minor_key(m) <= torch_minor_key(torch_major_minor)
        ]
        if lower_or_equal:
            return lower_or_equal[-1], common
        if common_stable:
            return common_stable[-1], common
        return None, common

    def version_tuple(version: str) -> tuple[int, int, int]:
        parts = version.split("+", 1)[0].split(".")
        nums = [int(p) if p.isdigit() else 0 for p in parts[:3]]
        while len(nums) < 3:
            nums.append(0)
        return tuple(nums)

    def latest_pypi_torch_version(target_minor: str) -> str:
        url = "https://pypi.org/pypi/torch/json"
        req = urllib.request.Request(url, headers={"User-Agent": "ECG-RAMBA-Colab"})
        with urllib.request.urlopen(req, timeout=60) as resp:
            payload = json.loads(resp.read().decode("utf-8"))
        versions = [
            version for version, files in payload.get("releases", {}).items()
            if version.startswith(target_minor + ".")
            and re.match(r"^[0-9]+\\.[0-9]+\\.[0-9]+$", version)
            and files
        ]
        if not versions:
            raise RuntimeError(f"No stable torch release found on PyPI for torch{target_minor}.")
        return sorted(versions, key=version_tuple)[-1]

    def pin_torch_if_needed() -> None:
        target_minor, supported = choose_supported_torch_minor()
        print("Mamba-supported torch minors:", supported)
        if target_minor == torch_major_minor:
            return
        if target_minor is None:
            raise RuntimeError(
                f"No common Mamba wheel support found for {py_tag}, {cuda_tag}, cxx11abi{abi_tag}. "
                "Use a different Colab runtime or build wheels manually."
            )
        if not AUTO_PIN_TORCH_FOR_MAMBA:
            raise RuntimeError(
                f"Current torch{torch_major_minor} has no matching Mamba wheels. "
                f"Set AUTO_PIN_TORCH_FOR_MAMBA=True or install torch{target_minor} manually."
            )

        target_version = latest_pypi_torch_version(target_minor)
        pin_manifest = {
            "reason": "Current Colab torch minor has no matching Mamba release wheels.",
            "current_torch_version": torch.__version__,
            "current_torch_minor": torch_major_minor,
            "target_torch_version": target_version,
            "target_torch_minor": target_minor,
            "supported_torch_minors": supported,
            "python_tag": py_tag,
            "cuda_tag": cuda_tag,
            "cxx11abi": abi_tag,
        }
        wheel_cache_dir.mkdir(parents=True, exist_ok=True)
        pin_path = wheel_cache_dir / "torch_runtime_pin.json"
        pin_path.write_text(json.dumps(pin_manifest, indent=2), encoding="utf-8")
        print(f"Current torch{torch_major_minor} has no compatible Mamba wheels.")
        print(f"Installing torch=={target_version} so Mamba wheels can use torch{target_minor}.")
        print(f"Wrote torch pin manifest: {pin_path}")
        subprocess.run(
            [sys.executable, "-m", "pip", "install", "-q", "--force-reinstall", f"torch=={target_version}"],
            check=True,
        )
        print("Torch was changed in this runtime. Restarting now; after reconnect, rerun the notebook from the top.")
        if RESTART_RUNTIME_AFTER_TORCH_PIN:
            os.kill(os.getpid(), 9)
        raise SystemExit("Restart runtime and rerun the notebook from the top.")

    def select_release_asset(repo: str, role: str) -> dict:
        rel = github_latest_release(repo)
        assets = rel.get("assets", [])
        matches = [a for a in assets if compatible_wheel(a["name"], role)]
        if matches:
            print(f"Selected {role} wheel from {repo} {rel.get('tag_name')}: {matches[0]['name']}")
            return matches[0]

        candidates = [
            a["name"] for a in assets
            if wheel_role(a["name"]) == role and py_tag in a["name"] and "linux_x86_64.whl" in a["name"]
        ]
        print(f"No compatible {role} wheel found in latest release {repo} {rel.get('tag_name')}.")
        print("Closest cp/linux candidates:")
        for name in candidates[:30]:
            print("  -", name)
        raise RuntimeError(
            f"Missing compatible {role} wheel for {py_tag}, torch{torch_major_minor}, "
            f"{cuda_tag}, cxx11abi{abi_tag}. Runtime and wheel tags must match."
        )

    def download_asset(asset: dict, out_dir: Path) -> Path:
        out_dir.mkdir(parents=True, exist_ok=True)
        name = asset["name"]
        out_path = out_dir / name
        if out_path.exists() and out_path.stat().st_size == int(asset.get("size", 0)):
            print(f"Reusing cached download: {out_path}")
            return out_path

        tmp_path = out_path.with_suffix(out_path.suffix + ".partial")
        print(f"Downloading {name}")
        print(f"  -> {out_path}")
        req = urllib.request.Request(asset["browser_download_url"], headers={"User-Agent": "ECG-RAMBA-Colab"})
        with urllib.request.urlopen(req, timeout=900) as resp, tmp_path.open("wb") as f:
            while True:
                chunk = resp.read(1024 * 1024)
                if not chunk:
                    break
                f.write(chunk)
        os.replace(tmp_path, out_path)
        return out_path

    pin_torch_if_needed()

    causal_wheel, mamba_wheel = select_cached_wheels()
    downloaded_assets = []

    if (causal_wheel is None or mamba_wheel is None) and DOWNLOAD_MAMBA_WHEELS_IF_MISSING:
        print("Compatible cached Mamba wheels are missing; downloading release wheels to Drive.")
        if causal_wheel is None:
            asset = select_release_asset("Dao-AILab/causal-conv1d", "causal")
            causal_wheel = download_asset(asset, wheel_cache_dir)
            downloaded_assets.append(asset)
        if mamba_wheel is None:
            asset = select_release_asset("state-spaces/mamba", "mamba")
            mamba_wheel = download_asset(asset, wheel_cache_dir)
            downloaded_assets.append(asset)

    if causal_wheel is None or mamba_wheel is None:
        raise FileNotFoundError(
            "Missing compatible causal_conv1d*.whl and/or mamba_ssm*.whl. "
            "Set DOWNLOAD_MAMBA_WHEELS_IF_MISSING=True or place matching wheels in the Drive cache."
        )

    manifest = {
        "python_tag": py_tag,
        "torch_version": torch.__version__,
        "torch_major_minor": torch_major_minor,
        "cuda_version": cuda_version,
        "cuda_tag": cuda_tag,
        "cxx11abi": abi_tag,
        "wheel_cache_dir": str(wheel_cache_dir),
        "causal_wheel": {
            "path": str(causal_wheel),
            "name": causal_wheel.name,
            "sha256": sha256_file(causal_wheel),
            "bytes": causal_wheel.stat().st_size,
        },
        "mamba_wheel": {
            "path": str(mamba_wheel),
            "name": mamba_wheel.name,
            "sha256": sha256_file(mamba_wheel),
            "bytes": mamba_wheel.stat().st_size,
        },
        "downloaded_assets": [
            {
                "name": a.get("name"),
                "url": a.get("browser_download_url"),
                "size": a.get("size"),
                "digest": a.get("digest"),
            }
            for a in downloaded_assets
        ],
    }
    manifest_path = wheel_cache_dir / "wheel_manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    print(f"Wrote wheel manifest: {manifest_path}")

    print("Installing Mamba wheels from Drive cache")
    print("  causal-conv1d:", causal_wheel.name)
    print("  mamba-ssm    :", mamba_wheel.name)
    subprocess.run([sys.executable, "-m", "pip", "install", "--no-deps", str(causal_wheel), "-q"], check=True)
    subprocess.run([sys.executable, "-m", "pip", "install", "--no-deps", str(mamba_wheel), "-q"], check=True)

    import mamba_ssm
    print("mamba_ssm import OK:", mamba_ssm.__file__)
else:
    print("Skipping mamba-ssm install. Ensure it is already available before prediction generation.")
"""
        ),
        markdown(
            "## Prediction Contract\n\n"
            "Every downstream metric script expects NPZ files with `y_true` and "
            "`y_prob`, both shaped `(N, C)`. Store prediction files under "
            "`reports/revision/predictions/`."
        ),
        code(
            """from pathlib import Path
import numpy as np

pred_dir = Path('reports/revision/predictions')
pred_dir.mkdir(parents=True, exist_ok=True)

for path in sorted(pred_dir.glob('*.npz')):
    data = np.load(path, allow_pickle=True)
    keys = sorted(data.files)
    print(path, keys)
    if {'y_true', 'y_prob'}.issubset(keys):
        print('  y_true:', data['y_true'].shape, 'y_prob:', data['y_prob'].shape)
"""
        ),
        markdown("## Generate OOF Predictions"),
        code(
            """RUN_OOF_EXPORT = True
BATCH_SIZE = 32
DEBUG_LIMIT_RECORDS = 0

command = (
    'python scripts/revision/01_generate_predictions.py '
    f'--dataset oof --checkpoint-kind best --batch-size {BATCH_SIZE}'
)
if DEBUG_LIMIT_RECORDS:
    command += f' --limit-records {DEBUG_LIMIT_RECORDS}'

if RUN_OOF_EXPORT:
    run(command)
else:
    print(f'OOF export disabled. Set RUN_OOF_EXPORT=True to execute: {command}')
"""
        ),
        markdown("## Verify OOF Prediction Outputs"),
        code(
            """expected = [
    Path('reports/revision/predictions/oof_full_predictions.npz'),
    Path('reports/revision/predictions/oof_full_slice_predictions.npz'),
    Path('reports/revision/metrics/oof_full_prediction_summary.json'),
]

for path in expected:
    print(path, 'exists=', path.exists(), 'size=', path.stat().st_size if path.exists() else None)

pred_path = expected[0]
if pred_path.exists():
    data = np.load(pred_path, allow_pickle=True)
    print('keys:', sorted(data.files))
    print('y_true:', data['y_true'].shape)
    print('y_prob:', data['y_prob'].shape)
    print('classes:', list(data['class_names'])[:5], '...', len(data['class_names']))
"""
        ),
        markdown("## External Prediction Commands"),
        code(
            """print('PTB-XL and CPSC/Georgia prediction exporters are the next implementation step.')
print('Expected future outputs:')
print('- reports/revision/predictions/ptbxl_full_predictions.npz')
print('- reports/revision/predictions/cpsc_full_predictions.npz')
"""
        ),
        markdown("## Re-run Inventory"),
        code("!python scripts/revision/05_artifact_inventory.py\n"),
    ]


def calibration_notebook() -> list[dict]:
    return [
        markdown("## Setup"),
        code(SETUP_CODE + "\n" + RUN_HELPER_CODE),
        markdown("## Run Calibration And Bootstrap CI"),
        code(
            """pred_dir = Path('reports/revision/predictions')
metric_dir = Path('reports/revision/metrics')
metric_dir.mkdir(parents=True, exist_ok=True)

prediction_files = sorted(pred_dir.glob('*.npz'))
if not prediction_files:
    print(f'No prediction NPZ files found under {pred_dir}. Run notebook 02 first.')

for pred in prediction_files:
    out = metric_dir / f'calibration_ci_{pred.stem}.json'
    cmd = f'python scripts/revision/04_calibration_ci.py --predictions {pred} --out {out} --n-boot 1000'
    run(cmd)
"""
        ),
        markdown("## Summarize Metric Files"),
        code(
            """for path in sorted(Path('reports/revision/metrics').glob('calibration_ci_*.json')):
    payload = json.loads(path.read_text(encoding='utf-8'))
    print('\\n' + str(path))
    print('shape:', payload.get('shape'))
    print('metrics:', payload.get('metrics'))
    print('calibration:', payload.get('calibration'))
"""
        ),
        code("!python scripts/revision/05_artifact_inventory.py\n"),
    ]


def baselines_notebook() -> list[dict]:
    return [
        markdown("## Setup"),
        code(SETUP_CODE + "\n" + RUN_HELPER_CODE),
        markdown(
            "## Minimum Fair Baseline Matrix\n\n"
            "A-level baselines: Full ECG-RAMBA, Raw Mamba, ResNet1D/CNN, "
            "MiniRocket-only, HRV-only. All must use the same split, "
            "preprocessing, threshold, and aggregation protocol."
        ),
        code(
            """import pandas as pd

registry = pd.read_csv('docs/revision_plan/experiment_registry.csv')
display(registry[registry['experiment_id'].isin(['EXP_BASE', 'EXP_PRED'])])

planned_outputs = [
    'reports/revision/metrics/baseline_summary.csv',
    'reports/revision/tables/table_baselines.csv',
]
for path in planned_outputs:
    print(path, 'exists=', Path(path).exists())
"""
        ),
        markdown("## Placeholder Commands"),
        code(
            """RUN_HEAVY = False

planned = {
    'MiniRocket-only': 'python scripts/revision/TBD_minirocket_only.py',
    'HRV-only': 'python scripts/revision/TBD_hrv_only.py',
    'ResNet1D/CNN': 'python scripts/revision/TBD_resnet1d_baseline.py',
    'Raw Mamba': 'python scripts/revision/TBD_raw_mamba_baseline.py',
}

for name, command in planned.items():
    if RUN_HEAVY:
        run(command, check=False)
    else:
        print(f'{name}: planned command -> {command}')
"""
        ),
    ]


def hrv_robustness_notebook() -> list[dict]:
    return [
        markdown("## Setup"),
        code(SETUP_CODE + "\n" + RUN_HELPER_CODE),
        markdown(
            "## HRV Domain Sensitivity And Minimum Robustness\n\n"
            "Outputs required by the revised plan: HRV-only result, HRV domain "
            "classifier AUC, duration/noise check, SNR 20/10/5 dB, random "
            "3-lead dropout, V1-V6 dropout, and 500->250 Hz sampling shift."
        ),
        code(
            """import pandas as pd

tasks = pd.read_csv('docs/revision_plan/task_board.csv')
display(tasks[tasks['id'].isin(['A6', 'B2'])])

for path in [
    'reports/revision/metrics/hrv_domain_summary.csv',
    'reports/revision/metrics/robustness_summary.csv',
    'reports/revision/tables/table_robustness.csv',
]:
    print(path, 'exists=', Path(path).exists())
"""
        ),
        markdown("## Placeholder Commands"),
        code(
            """RUN_HEAVY = False

planned = {
    'HRV domain classifier': 'python scripts/revision/TBD_hrv_domain_classifier.py',
    'Robustness stress tests': 'python scripts/revision/TBD_robustness_stress.py',
}

for name, command in planned.items():
    if RUN_HEAVY:
        run(command, check=False)
    else:
        print(f'{name}: planned command -> {command}')
"""
        ),
    ]


def pooling_representation_notebook() -> list[dict]:
    return [
        markdown("## Setup"),
        code(SETUP_CODE + "\n" + RUN_HELPER_CODE),
        markdown(
            "## Pooling Sensitivity And Representation Evidence\n\n"
            "This notebook addresses Power Mean Q=3 and the reduced claim "
            "`evidence consistent with morphology-rhythm separation`."
        ),
        code(
            """import pandas as pd

tasks = pd.read_csv('docs/revision_plan/task_board.csv')
display(tasks[tasks['id'].isin(['B1', 'B3'])])

for path in [
    'reports/revision/metrics/pooling_sensitivity.csv',
    'reports/revision/metrics/probing_summary.csv',
    'reports/revision/figures/representation_umap.png',
]:
    print(path, 'exists=', Path(path).exists())
"""
        ),
        markdown("## Placeholder Commands"),
        code(
            """RUN_HEAVY = False

planned = {
    'Pooling sensitivity': 'python scripts/revision/TBD_pooling_sensitivity.py',
    'Representation probing': 'python scripts/revision/TBD_representation_probe.py',
}

for name, command in planned.items():
    if RUN_HEAVY:
        run(command, check=False)
    else:
        print(f'{name}: planned command -> {command}')
"""
        ),
    ]


def freeze_notebook() -> list[dict]:
    return [
        markdown("## Setup"),
        code(SETUP_CODE + "\n" + RUN_HELPER_CODE),
        markdown("## Review Claim Evidence Map"),
        code(
            """import pandas as pd

claims = pd.read_csv('docs/revision_plan/claim_evidence_map.csv')
display(claims)
"""
        ),
        markdown("## Freeze Artifact Manifest"),
        code("!python scripts/revision/05_artifact_inventory.py\n"),
        markdown("## Final Checklist"),
        code(
            """task_board = pd.read_csv('docs/revision_plan/task_board.csv')
display(task_board[['id', 'priority', 'task', 'status', 'notebook', 'report_artifacts']])

print('\\nBefore manuscript use, verify:')
print('- Every table/figure number maps to a file under reports/revision/.')
print('- Every claim in claim_evidence_map.csv has evidence or fallback wording.')
print('- No final number comes only from notebook output without a saved artifact.')
print('- artifacts_manifest.json was generated after the final run.')
"""
        ),
    ]


def main() -> None:
    notebooks = {
        "00_colab_bootstrap.ipynb": ("00 Colab Bootstrap", bootstrap_notebook()),
        "01_a0_protocol_audit.ipynb": ("01 A0 Protocol Audit", a0_notebook()),
        "02_predictions_and_external_eval.ipynb": (
            "02 Predictions And External Evaluation",
            predictions_notebook(),
        ),
        "03_calibration_and_ci.ipynb": ("03 Calibration And CI", calibration_notebook()),
        "04_baselines_and_component_checks.ipynb": (
            "04 Baselines And Component Checks",
            baselines_notebook(),
        ),
        "05_hrv_domain_and_robustness.ipynb": (
            "05 HRV Domain And Robustness",
            hrv_robustness_notebook(),
        ),
        "06_pooling_and_representation.ipynb": (
            "06 Pooling And Representation",
            pooling_representation_notebook(),
        ),
        "07_results_freeze.ipynb": ("07 Results Freeze", freeze_notebook()),
    }

    for filename, (title, cells) in notebooks.items():
        write_notebook(NOTEBOOK_DIR / filename, title, cells)


if __name__ == "__main__":
    main()
