import React, { useRef, useState } from 'react';
import { Activity, CheckCircle2, AlertCircle, TrendingUp, Cpu, Download, Loader2 } from 'lucide-react';
import { motion } from 'framer-motion';
import clsx from 'clsx';
import html2canvas from 'html2canvas';
import jsPDF from 'jspdf';

const DiagnosisReport = ({ prediction }) => {
  const { diagnosis, confidence, model_used } = prediction;
  const componentRef = useRef(null);
  const [isExporting, setIsExporting] = useState(false);
  
  // Logic to determine status color and icon
  const isNormal = diagnosis?.toLowerCase().includes("normal");
  const isHighConf = confidence > 0.8;

  const StatusIcon = isNormal ? CheckCircle2 : AlertCircle;
  const statusColor = isNormal ? "text-emerald-600" : "text-amber-600";
  const statusBg = isNormal ? "bg-emerald-50" : "bg-amber-50";
  const statusBorder = isNormal ? "border-emerald-200" : "border-amber-200";

  const handleExportPDF = async () => {
    if (!componentRef.current) return;
    setIsExporting(true);

    try {
        const element = componentRef.current;
        const canvas = await html2canvas(element, { scale: 2, useCORS: true });
        const imgData = canvas.toDataURL('image/png');
        
        const pdf = new jsPDF('p', 'mm', 'a4');
        const pdfWidth = pdf.internal.pageSize.getWidth();
        const pdfHeight = (canvas.height * pdfWidth) / canvas.width;
        
        pdf.addImage(imgData, 'PNG', 0, 20, pdfWidth, pdfHeight);
        pdf.setFontSize(10);
        pdf.text("Generated by CardioAI - Clinical Suite", 10, 10);
        pdf.save(`ECG_Report_${Date.now()}.pdf`);
    } catch (err) {
        console.error("PDF Export failed:", err);
    } finally {
        setIsExporting(false);
    }
  };

  return (
    <motion.div 
      initial={{ opacity: 0, scale: 0.95 }}
      animate={{ opacity: 1, scale: 1 }}
      transition={{ duration: 0.4, type: "spring" }}
      className="bg-white/80 backdrop-blur-sm rounded-2xl shadow-xl shadow-blue-900/5 border border-white/50 overflow-hidden"
    >
      <div ref={componentRef} className="bg-white"> {/* Wrap content for clean PDF capture */}
          <div className="p-6">
            <div className="flex items-center justify-between mb-6">
                <h2 className="text-sm font-bold text-gray-400 uppercase tracking-widest flex items-center gap-2">
                    <Cpu className="w-4 h-4" />
                    AI Analysis Report
                </h2>
                <div className="px-3 py-1 bg-slate-100 rounded-full text-xs font-mono text-slate-500">
                   ID: {Math.random().toString(36).substr(2, 9).toUpperCase()}
                </div>
            </div>
            
            <div className="flex flex-col md:flex-row gap-8 items-center">
                
                {/* Main Diagnosis Badge */}
                <div className={clsx(
                    "flex-1 w-full p-6 rounded-2xl border-2 flex items-center gap-5 transition-all text-left",
                    statusBg, statusBorder
                )}>
                    <div className={clsx("p-4 rounded-xl shadow-sm bg-white", statusColor)}>
                        <StatusIcon className="w-10 h-10" />
                    </div>
                    <div>
                         <p className="text-sm font-bold opacity-60 uppercase mb-1">Diagnosis</p>
                         <h3 className={clsx("text-2xl font-black tracking-tight", isNormal ? "text-emerald-900" : "text-amber-900")}>
                            {diagnosis || "Unknown"}
                         </h3>
                         <p className="text-sm opacity-70 mt-1 font-medium">Based on Lead I analysis</p>
                    </div>
                </div>

                {/* Confidence Meter */}
                <div className="flex-1 w-full space-y-4">
                    <div className="flex items-end justify-between">
                         <div>
                            <p className="text-sm text-gray-500 font-medium mb-1 flex items-center gap-2">
                               <TrendingUp className="w-4 h-4 text-blue-500" />
                               Model Confidence
                            </p>
                            <div className="text-4xl font-black text-slate-800">
                               {(confidence * 100).toFixed(1)}<span className="text-lg text-slate-400 font-bold">%</span>
                            </div>
                         </div>
                         <div className="text-right">
                             <div className="text-xs font-medium text-slate-400">Model Architecture</div>
                             <div className="text-sm font-bold text-blue-600">{model_used}</div>
                         </div>
                    </div>

                    <div className="h-3 w-full bg-gray-100 rounded-full overflow-hidden relative">
                        <motion.div 
                           initial={{ width: 0 }}
                           animate={{ width: `${confidence * 100}%` }}
                           transition={{ duration: 1, ease: "circOut", delay: 0.2 }}
                           className={clsx(
                              "h-full rounded-full shadow-lg",
                              isHighConf ? "bg-gradient-to-r from-blue-500 to-indigo-600" : "bg-gradient-to-r from-amber-400 to-orange-500"
                           )}
                        />
                    </div>
                </div>
            </div>

            {/* AI Analysis & Recommendation Section */}
            {(prediction.explanation || prediction.recommendation) && (
                <div 
                    className="mt-6 pt-6 border-t border-gray-100 grid md:grid-cols-2 gap-6 text-left"
                >
                    <div>
                       <h4 className="text-xs font-bold text-gray-400 uppercase tracking-widest mb-2 flex items-center gap-2">
                          <Activity className="w-3 h-3" />
                          Clinical Explanation
                       </h4>
                       <p className="text-sm text-gray-600 leading-relaxed font-medium">
                          {prediction.explanation}
                       </p>
                    </div>
                    <div className="bg-blue-50/50 p-4 rounded-xl border border-blue-100">
                       <h4 className="text-xs font-bold text-blue-800 uppercase tracking-widest mb-2 flex items-center gap-2">
                          <CheckCircle2 className="w-3 h-3" />
                          Recommendation
                       </h4>
                       <p className="text-sm text-blue-900 leading-relaxed">
                          {prediction.recommendation}
                       </p>
                    </div>
                </div>
            )}
          </div>
      </div>
      
      {/* Footer Actions */}
      <div className="bg-gray-50/50 p-4 border-t border-gray-100 flex justify-end gap-3">
          <button 
            onClick={handleExportPDF}
            disabled={isExporting}
            className="px-4 py-2 text-sm font-bold text-white bg-slate-900 hover:bg-slate-800 rounded-lg shadow-lg shadow-slate-200 transition-all hover:-translate-y-0.5 active:translate-y-0 flex items-center gap-2"
          >
              {isExporting ? <Loader2 className="w-4 h-4 animate-spin" /> : <Download className="w-4 h-4" />}
              {isExporting ? "Generating..." : "Export PDF"}
          </button>
      </div>
    </motion.div>
  );
};

export default DiagnosisReport;
